// Code generated by ent, DO NOT EDIT.

package rest

import (
	ent "github.com/alfariiizi/vandor/internal/infrastructure/db"
)

// EagerLoadNotification eager-loads the edges of a Notification entity, if any edges
// were requested to be eager-loaded, based off associated annotations.
func EagerLoadNotification(query *ent.NotificationQuery) *ent.NotificationQuery {
	return query
}

// EagerLoadProduct eager-loads the edges of a Product entity, if any edges
// were requested to be eager-loaded, based off associated annotations.
func EagerLoadProduct(query *ent.ProductQuery) *ent.ProductQuery {
	return query
}

// EagerLoadSession eager-loads the edges of a Session entity, if any edges
// were requested to be eager-loaded, based off associated annotations.
func EagerLoadSession(query *ent.SessionQuery) *ent.SessionQuery {
	return query
}

// EagerLoadUser eager-loads the edges of a User entity, if any edges
// were requested to be eager-loaded, based off associated annotations.
func EagerLoadUser(query *ent.UserQuery) *ent.UserQuery {
	return query
}
