// Package user_service provides services for the user group.
// Code generated by Service Generator. DO NOT EDIT.
// Template: https://github.com/alfariiizi/go-service.
package user_service

import "go.uber.org/fx"

type UserService struct {
	GetUserPaginationOutput GetUserPaginationOutput
	GetUserPagination GetUserPagination
}

func NewUserService(
	getUserPaginationOutput GetUserPaginationOutput,
	getUserPagination GetUserPagination,
) UserService {
	return UserService{
		GetUserPaginationOutput: getUserPaginationOutput,
		GetUserPagination: getUserPagination,
	}
}

var Module = fx.Module(
	"user_service",
	fx.Provide(
		NewGetUserPaginationOutput,
		NewGetUserPagination,
		NewUserService,
	),
)
