// Code generated by vandor; DO NOT EDIT.
package job

import "go.uber.org/fx"

type Jobs struct {
    LogLove LogLove
    LogSystem LogSystem
}

func NewJobs(
    LogLove LogLove,
    LogSystem LogSystem,
) *Jobs {
    return &Jobs{
        LogLove: LogLove,
        LogSystem: LogSystem,
    }
}

var Module = fx.Module(
    "job",
    fx.Provide(
        NewLogLove,
        NewLogSystem,
        NewJobs,
    ),
)
