// Code generated by vandor; DO NOT EDIT.
package job

import "go.uber.org/fx"

type Jobs struct {
	LogSystem LogSystem
}

func NewJobs(
	LogSystem LogSystem,
) *Jobs {
	return &Jobs{
		LogSystem: LogSystem,
	}
}

var Module = fx.Module(
	"job",
	fx.Provide(
		NewLogSystem,
		NewJobs,
	),
	fx.Invoke(
		func(j LogSystem) {
			j.HTTPRegisterRoute()
		},
	),
)
