// Package auth_service provides services for the auth group.
// Code generated by Service Generator. DO NOT EDIT.
// Template: https://github.com/alfariiizi/vandor.
package auth_service

import "go.uber.org/fx"

type AuthService struct {
	Login Login
	Refresh Refresh
}

func NewAuthService(
	login Login,
	refresh Refresh,
) AuthService {
	return AuthService{
		Login: login,
		Refresh: refresh,
	}
}

var Module = fx.Module(
	"auth_service",
	fx.Provide(
		NewLogin,
		NewRefresh,
		NewAuthService,
	),
)
