// DO NOT EDIT - AUTO-GENERATED BY vandor
package seed

import (
	"context"

	"github.com/alfariiizi/vandor/internal/core/model"
	"github.com/alfariiizi/vandor/internal/infrastructure/db"
)

var seeders = []model.Seeder{
	UserSeeder{},
}

func RunAll(ctx context.Context, client *db.Client, group string) error {
	for _, s := range seeders {
		if group == "" || s.Group() == group {
			if err := s.Run(ctx, client); err != nil {
				return err
			}
		}
	}
	return nil
}

func RunOne(ctx context.Context, client *db.Client, name string) error {
	for _, s := range seeders {
		if s.Name() == name {
			return s.Run(ctx, client)
		}
	}
	return nil
}
