// Package route provides HTTP routes for the application.
// Code generated by HTTP Handler Generator. DO NOT EDIT.
// Template: https://github.com/alfariiizi/vandor.
package route

import (
	auth_handler "github.com/alfariiizi/vandor/internal/delivery/http/route/auth"
	system_handler "github.com/alfariiizi/vandor/internal/delivery/http/route/system"
	"go.uber.org/fx"
)

var Module = fx.Module(
	"route",
	fx.Invoke(
		auth_handler.NewLogin,
		auth_handler.NewLoginAdmin,
		auth_handler.NewRefresh,
		system_handler.NewHealth,
		system_handler.NewPing,
	),
)
