// Package route provides HTTP routes for the application.
// Code generated by HTTp Handler Generator. DO NOT EDIT.
// Template: https://github.com/alfariiizi/go-service.
package route

import (
	system_handler "github.com/alfariiizi/go-service/internal/delivery/http/route/system"
	user_handler "github.com/alfariiizi/go-service/internal/delivery/http/route/user"
	"go.uber.org/fx"
)

var Module = fx.Module(
	"route",
	fx.Invoke(
		system_handler.NewHealth,
		system_handler.NewPing,
		user_handler.NewGetUserPagination,
	),
)
