// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdminAuditLog is the predicate function for adminauditlog builders.
type AdminAuditLog func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
