// Package domain_entries provides all domain for the application.
// Code generated by Domain Generator. DO NOT EDIT.
// Template: https://github.com/alfariiizi/vandor
package domain_entries

import (
	domain_builder "github.com/alfariiizi/vandor/internal/core/domain/builder"
	domain "github.com/alfariiizi/vandor/internal/core/domain/model"
	"github.com/alfariiizi/vandor/internal/infrastructure/db"
	"go.uber.org/fx"
)

type Domain struct {
	Product domain_builder.Domain[*db.Product, *domain.Product]
	Session domain_builder.Domain[*db.Session, *domain.Session]
	User domain_builder.Domain[*db.User, *domain.User]
}

func NewDomain(client *db.Client) *Domain {
	return &Domain{
		Product: domain.NewProductDomain(client),
		Session: domain.NewSessionDomain(client),
		User: domain.NewUserDomain(client),
	}
}

var Module = fx.Module(
	"domain",
	fx.Provide(
		NewDomain,
	),
)
