// Package service provides all services for the application.
// Code generated by Service Generator. DO NOT EDIT.
// Template: https://github.com/alfariiizi/go-service.
package service

import (
	"go.uber.org/fx"
	system_service "github.com/alfariiizi/go-service/internal/core/service/system"
	user_service "github.com/alfariiizi/go-service/internal/core/service/user"
)

type Services struct {
	System system_service.SystemService
	User user_service.UserService
}

func NewServices(
	system system_service.SystemService,
	user user_service.UserService,
) *Services {
	return &Services{
		System: system,
		User: user,
	}
}

var Module = fx.Module(
	"service",
	fx.Provide(
		NewServices,
	),
	system_service.Module,
	user_service.Module,
)
