// Package service provides all services for the application.
// Code generated by Service Generator. DO NOT EDIT.
// Template: https://github.com/alfariiizi/vandor.
package service

import (
	"go.uber.org/fx"
	auth_service "github.com/alfariiizi/vandor/internal/core/service/auth"
	system_service "github.com/alfariiizi/vandor/internal/core/service/system"
)

type Services struct {
	System system_service.SystemService
	Auth auth_service.AuthService
}

func NewServices(
	auth auth_service.AuthService,
	system system_service.SystemService,
) *Services {
	return &Services{
		System: system,
		Auth: auth,
	}
}

var Module = fx.Module(
	"service",
	fx.Provide(
		NewServices,
	),
	auth_service.Module,
	system_service.Module,
)
