// Package usecase provide usecases for the application.
// Code generated by Usecase Generator. DO NOT EDIT.
// Template: https://github.com/alfariiizi/vandor.
package usecase

import (
	"go.uber.org/fx"
)

type Usecases struct {
	CreateAccessToken CreateAccessToken
}

func NewUsecases(
	createAccessToken CreateAccessToken,
) *Usecases {
	return &Usecases{
		CreateAccessToken: createAccessToken,
	}
}

var Module = fx.Module(
	"usecase",
	fx.Provide(
		NewCreateAccessToken,
		NewUsecases,
	),
)
