// Package usecase provide usecases for the application.
// Code generated by Usecase Generator. DO NOT EDIT.
// Template: https://github.com/alfariiizi/vandor.
package usecase

import (
	"go.uber.org/fx"
)

type Usecases struct {
	CreateAccessToken      CreateAccessToken
	CreateNotification     CreateNotification
	MarkAsReadNotification MarkAsReadNotification
}

func NewUsecases(
	createAccessToken CreateAccessToken,
	createNotification CreateNotification,
	markAsReadNotification MarkAsReadNotification,
) *Usecases {
	return &Usecases{
		CreateAccessToken:      createAccessToken,
		CreateNotification:     createNotification,
		MarkAsReadNotification: markAsReadNotification,
	}
}

var Module = fx.Module(
	"usecase",
	fx.Provide(
		NewCreateAccessToken,
		NewCreateNotification,
		NewMarkAsReadNotification,
		NewUsecases,
	),
)
