// Package usecase provide usecases for the application.
// Code generated by Usecase Generator. DO NOT EDIT.
// Template: https://github.com/alfariiizi/go-service.
package usecase

import (
	"go.uber.org/fx"
)

type Usecases struct{}

func NewUsecases() *Usecases {
	return &Usecases{}
}

var Module = fx.Module(
	"usecase",
	fx.Provide(
		NewUsecases,
	),
)
