// Code generated by vandor; DO NOT EDIT.
package asynq

import (
	"context"
	"encoding/json"

	"github.com/alfariiizi/vandor/internal/core/job"
	"github.com/hibiken/asynq"
)

func registerJobHandlers(mux *asynq.ServeMux, jobs *job.Jobs) {
	mux.HandleFunc("job:log_system", func(ctx context.Context, t *asynq.Task) error {
		var payload job.LogSystemPayload
		if err := json.Unmarshal(t.Payload(), &payload); err != nil {
			return err
		}
		return jobs.LogSystem.Handle(ctx, payload)
	})
}
