// Package system_service provides services for the system group.
// Code generated by Service Generator. DO NOT EDIT.
// Template: https://github.com/alfariiizi/vandor.
package system_service

import "go.uber.org/fx"

type SystemService struct {
	Health Health
	Ping Ping
}

func NewSystemService(
	health Health,
	ping Ping,
) SystemService {
	return SystemService{
		Health: health,
		Ping: ping,
	}
}

var Module = fx.Module(
	"system_service",
	fx.Provide(
		NewHealth,
		NewPing,
		NewSystemService,
	),
)
